# Generated by Django 4.2.7 on 2025-11-28 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Instagram username without @', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, help_text='Last time posts were fetched for this account', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subreddit name without r/ prefix', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreddits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(help_text='Full Reddit post URL', max_length=500, unique=True)),
                ('score', models.IntegerField(default=0, help_text='Reddit upvote score')),
                ('body', models.TextField(blank=True, help_text='Post body text')),
                ('flair', models.CharField(blank=True, help_text='Reddit post flair', max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, help_text='When this post was scraped')),
                ('keywords_extracted', models.BooleanField(default=False, help_text='Whether keywords have been extracted from this post')),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.subreddit')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='RedditKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Extracted keyword/phrase', max_length=255)),
                ('similarity', models.FloatField(help_text='Similarity score (0.0 to 1.0) indicating how well the keyword represents the post')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.redditpost')),
            ],
            options={
                'ordering': ['-similarity', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, help_text='Unique Instagram post ID', max_length=255)),
                ('caption', models.TextField(blank=True, help_text='Post caption/description')),
                ('taken_at', models.DateTimeField(help_text='When the post was originally created on Instagram')),
                ('image_url', models.URLField(blank=True, help_text='URL to the post image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this post was added to our database')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.instagramaccount')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.AddIndex(
            model_name='redditpost',
            index=models.Index(fields=['keywords_extracted', '-scraped_at'], name='core_reddit_keyword_422279_idx'),
        ),
        migrations.AddIndex(
            model_name='redditkeyword',
            index=models.Index(fields=['-similarity'], name='core_reddit_similar_1cb281_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instagrampost',
            unique_together={('account', 'post_id')},
        ),
        migrations.AlterUniqueTogether(
            name='instagramaccount',
            unique_together={('username', 'user')},
        ),
    ]
