# Generated by Django 4.2.7 on 2025-11-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Whether this post is a video'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='like_count',
            field=models.IntegerField(default=0, help_text='Number of likes on the post'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='post_code',
            field=models.CharField(blank=True, help_text='Instagram post shortcode for URL', max_length=255),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='video_url',
            field=models.URLField(blank=True, help_text="URL to the post video if it's a video", max_length=500),
        ),
    ]
