# Generated by Django 4.2.7 on 2025-11-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instagrampost_is_video_instagrampost_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='carousel_media_count',
            field=models.IntegerField(default=0, help_text='Number of media items in carousel'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='is_carousel',
            field=models.BooleanField(default=False, help_text='Whether this post is a carousel with multiple media'),
        ),
        migrations.CreateModel(
            name='InstagramCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_index', models.IntegerField(help_text='Index of this item in the carousel (0-based)')),
                ('image_url', models.URLField(blank=True, help_text='URL to the image if this is an image', max_length=500)),
                ('video_url', models.URLField(blank=True, help_text='URL to the video if this is a video', max_length=500)),
                ('is_video', models.BooleanField(default=False, help_text='Whether this carousel item is a video')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='core.instagrampost')),
            ],
            options={
                'ordering': ['item_index'],
                'unique_together': {('post', 'item_index')},
            },
        ),
    ]
