# Generated by Django 4.2.7 on 2025-11-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instagrampost_carousel_media_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='comment_count',
            field=models.IntegerField(default=0, help_text='Number of comments on the post'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of views on the post (for videos/Reels)'),
        ),
    ]
