# Generated by Django 4.2.7 on 2025-11-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instagrampost_comment_count_instagrampost_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='view_count',
        ),
    ]
