# Generated by Django 4.2.7 on 2025-12-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_instagrampost_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='play_count',
            field=models.IntegerField(default=0, help_text='Number of plays/views on the post (for reels/videos)'),
        ),
    ]
