# Generated by Django 4.2.7 on 2025-12-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_instagrampost_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='is_reel',
            field=models.BooleanField(default=False, help_text='Whether this post is a reel (Instagram Reels)'),
        ),
    ]
