# Generated by Django 4.2.7 on 2025-12-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_instagrampost_is_reel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Extracted keyword/phrase', max_length=255)),
                ('similarity', models.FloatField(help_text='Similarity score (0.0 to 1.0) indicating how well the keyword represents the post')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-similarity', 'keyword'],
            },
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='keywords_extracted',
            field=models.BooleanField(default=False, help_text='Whether keywords have been extracted from this post'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['keywords_extracted', '-taken_at'], name='core_instag_keyword_4289ff_idx'),
        ),
        migrations.AddField(
            model_name='instagramkeyword',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.instagrampost'),
        ),
        migrations.AddIndex(
            model_name='instagramkeyword',
            index=models.Index(fields=['-similarity'], name='core_instag_similar_13e938_idx'),
        ),
    ]
