# Generated by Django 4.2.7 on 2025-12-08 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_instagramkeyword_instagrampost_keywords_extracted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Twitter username without @', max_length=255)),
                ('rest_id', models.CharField(blank=True, help_text='Twitter user rest_id (used for API calls)', max_length=255)),
                ('name', models.CharField(blank=True, help_text='Twitter display name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Twitter profile description')),
                ('followers_count', models.IntegerField(default=0, help_text='Number of followers')),
                ('following_count', models.IntegerField(default=0, help_text='Number of accounts following')),
                ('tweet_count', models.IntegerField(default=0, help_text='Total number of tweets')),
                ('verified', models.BooleanField(default=False, help_text='Whether the account is verified')),
                ('profile_image_url', models.URLField(blank=True, help_text='Profile image URL', max_length=500)),
                ('profile_banner_url', models.URLField(blank=True, help_text='Profile banner URL', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, help_text='Last time tweets were fetched for this account', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('username', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TwitterTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(db_index=True, help_text='Unique Twitter tweet ID', max_length=255)),
                ('text', models.TextField(help_text='Tweet text content')),
                ('created_at', models.DateTimeField(help_text='When the tweet was originally created on Twitter')),
                ('favorite_count', models.IntegerField(default=0, help_text='Number of favorites/likes on the tweet')),
                ('retweet_count', models.IntegerField(default=0, help_text='Number of retweets')),
                ('reply_count', models.IntegerField(default=0, help_text='Number of replies')),
                ('quote_count', models.IntegerField(default=0, help_text='Number of quote tweets')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views on the tweet')),
                ('media', models.JSONField(blank=True, default=list, help_text='List of media attachments (photos, videos, etc.)')),
                ('hashtags', models.JSONField(blank=True, default=list, help_text='List of hashtags in the tweet')),
                ('mentions', models.JSONField(blank=True, default=list, help_text='List of mentioned usernames')),
                ('urls', models.JSONField(blank=True, default=list, help_text='List of URLs in the tweet')),
                ('is_retweet', models.BooleanField(default=False, help_text='Whether this is a retweet')),
                ('is_quote', models.BooleanField(default=False, help_text='Whether this is a quote tweet')),
                ('lang', models.CharField(blank=True, help_text='Tweet language code', max_length=10)),
                ('created_at_db', models.DateTimeField(auto_now_add=True, help_text='When this tweet was added to our database')),
                ('keywords_extracted', models.BooleanField(default=False, help_text='Whether keywords have been extracted from this tweet')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='core.twitteraccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['keywords_extracted', '-created_at'], name='core_twitte_keyword_67630d_idx')],
                'unique_together': {('account', 'tweet_id')},
            },
        ),
    ]
