# Generated by Django 4.2.7 on 2025-12-09 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_twitteraccount_twittertweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Unified username (case-insensitive)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_usernames', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='social_username',
            field=models.ForeignKey(blank=True, help_text='Linked unified username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to='core.socialusername'),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='social_username',
            field=models.ForeignKey(blank=True, help_text='Linked unified username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_accounts', to='core.socialusername'),
        ),
        migrations.AddIndex(
            model_name='socialusername',
            index=models.Index(fields=['user', 'username'], name='core_social_user_id_f3157c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialusername',
            unique_together={('username', 'user')},
        ),
    ]
