# Generated by Django 4.2.7 on 2025-12-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_social_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Whether this post contains a video'),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='media_url',
            field=models.URLField(blank=True, help_text='Media URL (image or video)', max_length=500),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='post_type',
            field=models.CharField(blank=True, help_text='Post type: self, link, image, video, gallery', max_length=50),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL', max_length=500),
        ),
    ]
