# Generated by Django 4.2.7 on 2025-12-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_reddit_post_media_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Extracted keyword/phrase', max_length=255)),
                ('similarity', models.FloatField(blank=True, help_text='Similarity score (0.0 to 1.0) indicating how well the keyword represents the tweet. Null for Together AI keywords.', null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-extracted_at', 'keyword'],
            },
        ),
        migrations.RemoveIndex(
            model_name='twittertweet',
            name='core_twitte_keyword_67630d_idx',
        ),
        migrations.AlterField(
            model_name='instagramkeyword',
            name='similarity',
            field=models.FloatField(blank=True, help_text='Similarity score (0.0 to 1.0) indicating how well the keyword represents the post. Null for Together AI keywords.', null=True),
        ),
        migrations.AlterField(
            model_name='redditkeyword',
            name='similarity',
            field=models.FloatField(blank=True, help_text='Similarity score (0.0 to 1.0) indicating how well the keyword represents the post', null=True),
        ),
        migrations.AddField(
            model_name='twitterkeyword',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.twittertweet'),
        ),
        migrations.AddIndex(
            model_name='twitterkeyword',
            index=models.Index(fields=['-extracted_at'], name='core_twitte_extract_c4feea_idx'),
        ),
    ]
