# Generated by Django 4.2.7 on 2025-12-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_add_twitter_keyword_and_nullable_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoIdeaExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('source_type', models.CharField(db_index=True, help_text="Source platform: 'instagram' or 'twitter'", max_length=20)),
                ('source_id', models.IntegerField(db_index=True, help_text='ID of the source post or tweet')),
                ('video_analysis', models.JSONField(help_text='Video analysis containing id, title, duration, keywords, context, transcript')),
                ('video_ideas', models.JSONField(help_text='Array of 5 generated video ideas')),
                ('best_idea', models.JSONField(help_text='The selected best idea from the generated ideas')),
                ('video_prompt', models.JSONField(help_text='Video generation prompt with prompt, negative_prompt, and shot_list')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, help_text='When the extraction was performed')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-extracted_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='core_videoi_source__90b839_idx'), models.Index(fields=['-extracted_at'], name='core_videoi_extract_eb479f_idx')],
                'unique_together': {('source_type', 'source_id')},
            },
        ),
    ]
