# Generated by Django 4.2.7 on 2025-12-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_videoideaextraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaVideoPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_id', models.CharField(db_index=True, help_text='UUID of the specific idea from video_ideas array', max_length=255)),
                ('idea_title', models.CharField(help_text='Title of the idea for easy reference', max_length=500)),
                ('video_prompt', models.JSONField(help_text='Video generation prompt with prompt, negative_prompt, and shot_list (with timestamps)')),
                ('source_type', models.CharField(db_index=True, help_text="Source platform: 'instagram' or 'twitter'", max_length=20)),
                ('source_id', models.IntegerField(db_index=True, help_text='ID of the source post or tweet')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the prompt was generated')),
                ('extraction', models.ForeignKey(help_text='The video extraction this prompt was generated from', on_delete=django.db.models.deletion.CASCADE, related_name='idea_prompts', to='core.videoideaextraction')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['extraction', 'idea_id'], name='core_ideavi_extract_4a0f24_idx'), models.Index(fields=['source_type', 'source_id'], name='core_ideavi_source__b9d781_idx'), models.Index(fields=['-generated_at'], name='core_ideavi_generat_14833d_idx')],
                'unique_together': {('extraction', 'idea_id')},
            },
        ),
    ]
